# fly.toml app configuration file generated for memolink-server on 2025-10-15T19:29:57+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memolink-server'
primary_region = 'sin'

[build]


[env]
  PORT = "5001"

[processes]
  app = "npm run start"
  worker = "npm run start:worker"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[checks]]
  name = "healthcheck"
  grace_period = "30s"
  interval = "15s"
  method = "get"
  path = "/monitoring/health"
  port = 5001
  timeout = "10s"
  type = "http"
